### ISSUE TITLE
Feature Request: macOs support

### ISSUE THREAD

**Issue by esDotDev** [xinlake/armoury#1]
Would be nice if we could use this package to control both windows and mac.

**Comment by xinlake** [comment]
This repository contains several packages, I'm not sure which one are you talking about?

**Comment by xinlake** [comment]
> Would be nice if we could use this package to control both windows and mac.

This repository contains several packages, which one are you talking about?

**Comment by xinlake** [comment]
@esDotDev 
This repository contains several packages, which one are you talking about?

**Comment by esDotDev** [comment]
Ah sorry, referring to this one: https://pub.dev/packages/window_interface

The issues link from pub.dev brought me here.

**Comment by xinlake** [comment]
@esDotDev 
It's okay, you are welcome. I personally don't have any plans to support Mac or iOS, but contributions are welcome.

**Comment by esDotDev** [comment]
Sounds good! I've found this pkg which seems to do what I need https://pub.dev/packages/desktop_window
